---
- name: copy smart panda app
  copy:
    src: smartpanda-app
    dest: /tmp/
    owner: root
    group: root
    mode: 0755

- name: update apt cache
  apt:
    update-cache: yes

- name: install nodejs, redis and npm
  apt:
    name: "{{ item  }}"
    state: present
  with_items:
     - nodejs
     - redis
     - npm

- name: create /etc/redis/ dir
  file:
    path: /etc/redis
    state: directory
	
- name: make sure redis is configured properly
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf

- name: install npm dependencies
  npm:
    path: /tmp/smartpanda-app
	
- name: configure the code to run as a service
  template:
    src: smartpanda.conf.js
    dest: /etc/init/smartpanda.conf

- name: make sure redis and smartpanda are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
     - redis
     - smartpanda	
	
- name: make sure that the service is working:
  uri:
     url: localhost:8080/counter
